# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2pEynGKYqXuz_72elHDdqvpfPmA-QQb
"""

rint ("Hello World")

"""my first python code created in colab"""

print ("Hello World")

"""my first python code in colab"""